module.exports = {
  'period-search': require('./PeriodSearch'),
  'authority-search': require('./AuthoritySearch'),
  'dataset-statistics': require('./Statistics'),
  'windowed-period-list': require('./WindowedPeriodList'),
  'authority-list': require('./AuthorityList'),
  'time-cutoff': require('./HumanTimeCheckmark'),
  'timespan-visualization': require('./Timeline'),
  'spatial-visualization': require('./CoverageMap'),
  'place-filter': require('./PlaceFilter'),
  'time-filter': require('./TimeFilter'),
  'facets': require('./Facets'),
  'period-detail': require('./PeriodDetail'),
  'authority-detail': require('./AuthorityDetail'),
  'authority-period-detail': require('./AuthorityPeriodDetail'),
}
