module.exports = [
  'USER_LOGIN',
  'USER_LOGOUT',

  'REQUEST_AVAILABLE_BACKENDS',
  'REQUEST_ADD_BACKEND',
  'REQUEST_DELETE_BACKEND',
  'REQUEST_GET_BACKEND',

  'SET_CURRENT_BACKEND',
  'UNSET_CURRENT_BACKEND',
]
