"use strict";

exports.actions = {
  GET_ALL_BACKENDS: 'GET_ALL_BACKENDS',

  GET_BACKEND: 'GET_BACKEND',
  CREATE_BACKEND: 'CREATE_BACKEND',
  UPDATE_BACKEND: 'UPDATE_BACKEND',
  DELETE_BACKEND: 'DELETE_BACKEND',
  GENERATE_DATASET_PATCH: 'GENERATE_DATASET_PATCH',

  UNSET_CURRENT_BACKEND: 'UNSET_CURRENT_BACKEND',
}

exports.backends = {
  WEB: 'WEB',
  WEB_ANONYMOUS: 'WEB_ANONYMOUS',
  FILE: 'FILE',
  MEMORY: 'MEMORY',
  INDEXED_DB: 'INDEXED_DB',
  CANONICAL: 'CANONICAL',
}
