module.exports = {
  SYNC: 'SYNC',
  MULTIPLE: 'MULTIPLE',

  ADD_PERIOD_COLLECTION: 'ADD_PERIOD_COLLECTION',
  REMOVE_PERIOD_COLLECTION: 'REMOVE_PERIOD_COLLECTION',
  CHANGE_PERIOD_COLLECTION: 'CHANGE_PERIOD_COLLECTION',

  ADD_PERIOD: 'ADD_PERIOD',
  REMOVE_PERIOD: 'REMOVE_PERIOD',
  CHANGE_PERIOD: 'CHANGE_PERIOD',

  PUSH: 'PUSH',
  PULL: 'PULL',
}
