name: end-to-end tests
on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Dispatching end-to-end tests against $GITHUB_REF_NAME"
    - name: "Dispatch workflow"
      id: dispatch
      uses: mathze/workflow-dispatch-action@v1
      with:
        owner: periodo
        repo: periodo-tests
        ref: master
        token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        use-marker-step: true
        workflow-name: run-tests-on-branch.yml
        payload: |
          { "client_branch": "${{  github.ref_name }}" }
    - name: "Wait for workflow completion"
      uses: mathze/workflow-dispatch-action@v1
      with:
        token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        run-id: ${{ steps.dispatch.outputs.run-id }}
        fail-on-error: true
