name: end-to-end tests
on: [push]
jobs:
  dispatch-and-wait:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Dispatching end-to-end tests against $GITHUB_REF_NAME"
    - name: "Dispatch workflow"
      id: dispatch
      uses: mathze/workflow-dispatch-action@v1
      with:
        owner: periodo
        repo: periodo-tests
        ref: master
        token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        use-marker-step: true
        workflow-name: run-tests-on-branch.yml
        payload: |
          { "client_branch": "${{  github.ref_name }}" }
    - run: echo 'Workflow log at https://github.com/periodo/periodo-tests/actions/runs/${{ steps.dispatch.outputs.run-id }}'
    - name: "Wait for workflow completion"
      id: wait
      uses: mathze/workflow-dispatch-action@v1
      with:
        owner: periodo
        repo: periodo-tests
        ref: master
        token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        run-id: ${{ steps.dispatch.outputs.run-id }}
        fail-on-error: true
    - name: "Check result"
      run: |
        if [[ "completed" != "${{ steps.wait.outputs.run-status }}" ]] ||
           [[ "failure" != "${{ steps.wait.outputs.run-conclusion }}" ]] ||
           [[ false -ne ${{ steps.wait.outputs.failed }} ]]; then
           echo "Run-Status should be <completed> but was <${{ steps.wait.outputs.run-status }}>"
           echo "Run-Conclusion should be <failure> but was <${{ steps.wait.outputs.run-conclusion }}>"
           echo "Failed should be <false> but was <${{ steps.wait.outputs.failed }}>"
           exit 1
        else
          echo "Checks passed"
        fi
